name: Publish

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # Update the language picker in index.hbs to link new languages.
  LANGUAGES: bn da de es fa fr it ja ko pt-BR vi zh-CN zh-TW

jobs:
  publish:
    runs-on: ubuntu-22.04-64core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need the full history for build.sh below.

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Install mdbook
        uses: ./.github/workflows/install-mdbook

      - name: Build course in English
        run: .github/workflows/build.sh en book

      - name: Build all translations
        run: |
          for po_lang in ${{ env.LANGUAGES }}; do
              .github/workflows/build.sh $po_lang book/$po_lang
              mv book/$po_lang/html book/html/$po_lang
          done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/html
